INSERT INTO plants (plant_id, plant_name, scientific_name, care_difficulty, light_needs, prefers_humidity, pet_safe, is_unusual, hanging_basket, is_succulent, care_instructions)
VALUES (DEFAULT, 'Snake Plant', 'Sansevieria', 'Beginner', 'Low', false, false, false, false, true, 'This plant thrives on neglect!  Allow it to dry out completely between waterings.'),
       (DEFAULT, 'Bromeliad', 'Bromeliad', 'Beginner', 'Medium', true, true, true, false, false, 'Bromeliads are a large family of colorful, exotic looking tropical plants.  They prefer daily misting and evenly moist soil.'),
       (DEFAULT, 'Chinese Money Plant', 'Pilea Peperomioides', 'Beginner', 'Medium', false, true, false, false, false, 'Thrives in bright, indirect light.  Keep soil lightly moist to the touch.'),
       (DEFAULT, 'Nerve Plant', 'Fittonia', 'Beginner', 'Low', true, true, false, true, false, 'Fittonia come in a variety of colors.  Keep the soil evenly moist, and mist daily.  Tolerant of low light, but will thrive in bright, indirect light.'),
       (DEFAULT, 'Devil''s Ivy', 'Pothos', 'Beginner', 'Low', true, false, false, true, false, 'Pothos do well in almost any light condition.  Mist occasionally, and water when the top of the soil feels dry to the touch.'),
       (DEFAULT, 'Spider Plant', 'Chlorophytum Comosum', 'Beginner', 'Medium', true, true, false, true, false, 'Use only filtered water to avoid browning of leaf tips.  Water when top inhch of soil feels dry.'),
       (DEFAULT, 'Tropical Pitcher Plant', 'Nepenthes', 'Intermediate', 'Medium', true, true, true, true, false, 'Mist daily and keep soil evenly moist.  Use only filtered water to avoid discoloration.  Plant will produce more pitchers in bright, indirect light.'),
       (DEFAULT, 'Heart Leaf Philodendron', 'Philodendron Micans', 'Beginner', 'Medium', true, false, false, true, false, 'Prefers bright, indirect light.  Water when top inch of soil feels dry, mist daily is possible.'),
       (DEFAULT, 'Philodendron Brazil', 'Philodendron Brazil', 'Beginner', 'Medium', true, false, true, true, false, 'Prefers bright, indirect light.  Water when top inch of soil feels dry, mist daily is possible.'),
       (DEFAULT, 'Dumb Cane', 'Dieffenbachia', 'Beginner', 'Low', true, false, false, false, false, 'Mist daily if possible.  Water when top inch of soil is dry.  Keep out of direct sunlight.');

INSERT INTO plants (plant_id, plant_name, scientific_name, care_difficulty, light_needs, prefers_humidity, pet_safe, is_unusual, hanging_basket, is_succulent, care_instructions)
VALUES (DEFAULT, 'Chinese Evergreen', 'Aglaonema', 'Beginner', 'Low', true, false, false, false, false, 'Allow your aglaonema to dry out in between waterings, but mist daily to maintain humidity.  Green varieties do well in low light, colorful varieties prefer bright, indirect light.'),
       (DEFAULT, 'Prayer Plant', 'Maranta', 'Expert', 'Medium', true, true, true, true, false, 'Prayer plants are beautiful but fussy.  Mist daily to maintain humidity.  Prefers medium to bright, indirect light. Keep soil evenly moist, but not soggy.  Use only filtered water.'),
       (DEFAULT, 'Rattlesnake Plant', 'Calathea Lancifolia', 'Intermediate', 'Low', true, true, false, false, false, 'The least fussy of the calathea family. Mist daily and keep soil evenly moist.  Use only filtered water.'),
       (DEFAULT, 'Pinstripe Calathea', 'Calathea Ornata', 'Expert', 'Medium', true, true, true, false, false, 'Mist daily and keep soil evenly moist.  Use only filtered water.  Prefers bright, indirect light.  Calatheas can sense your fear.'),
       (DEFAULT, 'Round-Leaf Calathea', 'Calathea Orbifolia', 'Expert', 'Medium', true, true, true, false, false, 'Mist daily and keep soil evenly moist.  Use only filtered water.  Prefers bright, indirect light.  Calatheas can sense your fear.'),
       (DEFAULT, 'Peacock Calathea', 'Calathea Makoyana', 'Expert', 'Medium', true, true, true, false, false, 'Mist daily and keep soil evenly moist.  Use only filtered water.  Prefers bright, indirect light.  Calatheas can sense your fear.'),
       (DEFAULT, 'Calathea Freddie', 'Calathea Freddie', 'Expert', 'Medium', true, true, true, false, false, 'Mist daily and keep soil evenly moist.  Use only filtered water.  Prefers bright, indirect light.  Calatheas can sense your fear.'),
       (DEFAULT, 'Calathea Medallion', 'Calathea Roseopicta', 'Expert', 'Medium', true, true, true, false, false, 'Mist daily and keep soil evenly moist.  Use only filtered water.  Prefers bright, indirect light.  Calatheas can sense your fear.'),
       (DEFAULT, 'Calathea Burle Marx', 'Calathea Burle Marxii', 'Expert', 'Medium', true, true, true, false, false, 'Mist daily and keep soil evenly moist.  Use only filtered water.  Prefers bright, indirect light.  Calatheas can sense your fear.'),
       (DEFAULT, 'Calathea Vittata', 'Calathea Vittata', 'Expert', 'Medium', true, true, true, false, false, 'Mist daily and keep soil evenly moist.  Use only filtered water.  Prefers bright, indirect light.  Calatheas can sense your fear.'),
       (DEFAULT, 'Stromanthe Triostar', 'Stromanthe Triostar', 'Expert', 'Medium', true, true, true, false, false, 'Mist daily and keep soil evenly moist.  Use only filtered water.  Prefers bright, indirect light.  Calatheas can sense your fear.');

INSERT INTO plants (plant_id, plant_name, scientific_name, care_difficulty, light_needs, prefers_humidity, pet_safe, is_unusual, hanging_basket, is_succulent, care_instructions)
VALUES (DEFAULT, 'Lemon Lime Dracaena', 'Dracaena Deremensis', 'Beginner', 'Low', true, false, false, false, false, 'Dracaenas can tolerate a fair amount of neglect.  Mist daily and keep soil evenly, lightly moist, but not wet or soggy.  Use only filtered water.'),
       (DEFAULT, 'Janet Craig', 'Dracaena Deremensis', 'Beginner', 'Low', true, false, false, false, false, 'Dracaenas can tolerate a fair amount of neglect.  Mist daily and keep soil evenly, lightly moist, but not wet or soggy.  Use only filtered water.'),
       (DEFAULT, 'Corn Plant', 'Dracaena Fragrans', 'Beginner', 'Low', true, false, false, false, false, 'Dracaenas can tolerate a fair amount of neglect.  Mist daily and keep soil evenly, lightly moist, but not wet or soggy.  Use only filtered water.'),
       (DEFAULT, 'Dragon Tree', 'Dracaena Marginata', 'Beginner', 'Low', true, false, false, false, false, 'Dracaenas can tolerate a fair amount of neglect.  Mist daily and keep soil evenly, lightly moist, but not wet or soggy.  Use only filtered water.'),
       (DEFAULT, 'Lucky Bamboo', 'Dracaena Sanderiana', 'Beginner', 'Low', true, false, false, false, false, 'Commonly called lucky bamboo, this is actually a variety of Dracaena. Change water weekly.'),
       (DEFAULT, 'Crown of Thorns', 'Euphorbia Milii', 'Beginner', 'High', false, false, true, false, true, 'Keep in a sunny window.  Use well draining soil and water when the top 1-2 inches of soil are dry.  Fertilize regularly during the growing season.'),
       (DEFAULT, 'Madagascar Jewel', 'Euphorbia Leuconeura', 'Intermediate', 'Medium', false, false, true, false, true, 'Use well draining soil, and water thoroughly when to 1-2 inches of soil is dry.  Prefers bright, indirect light.  Poisonous to pets and children.'),
       (DEFAULT, 'Madagascar Palm', 'Pachypodium Lamerei', 'Intermediate', 'High', false, false, true, false, true, 'Prefers full sun.  Allow soil to dry out in bewteen waterings.'),
       (DEFAULT, 'Lifesaver Plant', 'Huernia', 'Intermediate', 'Medium', false, false, true, false, true, 'This family of succulents produces striking, foul smelling flowers.  Use soil with excellent drainage, and allow to dry out in between waterings. Prefers medium indirect light.'),
       (DEFAULT, 'Christmas Cactus', 'Schlumbergera Bridgessii', 'Beginner', 'Medium', false, true, false, true, true, 'Prefers more moisture than many other cacti.  Keep soil slightly moist, but not soggy. Keep out of direct sunlight.'),
       (DEFAULT, 'Orchid Cactus', 'Epiphyllum', 'Beginner', 'Medium', false, true, true, true, true, 'Prefers more moisture than many other cacti.  Keep soil slightly moist, but not soggy. Keep out of direct sunlight.'),
       (DEFAULT, 'Mistletoe Cactus', 'Rhipsalis Baccifera', 'Beginner', 'Medium', false, true, true, true, true, 'Prefers more moisture than many other cacti.  Keep soil slightly moist, but not soggy. Keep out of direct sunlight.');

       